server:
  port: 8082
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

  application:
    name: DRAFT-SERVICE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5050/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost
